# This file was generated by GoReleaser. DO NOT EDIT.
cask "epok" do
  desc "A CLI for working with Unix Timestamps & Timezones"
  homepage "https://github.com/DanStough/epok"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "epok"
  manpage "manpages/epok.1.gz"
  bash_completion "completions/epok.bash"
  zsh_completion "completions/epok.zsh"
  fish_completion "completions/epok.fish"

  on_macos do
    on_intel do
      url "https://github.com/DanStough/epok/releases/download/v0.1.2/epok_Darwin_x86_64.tar.gz"
      sha256 "f93d92753c8f951050278267417a1c0174ec69ea60b98370d743aa2be3ff19e0"
    end
    on_arm do
      url "https://github.com/DanStough/epok/releases/download/v0.1.2/epok_Darwin_arm64.tar.gz"
      sha256 "66e5ca6ed3101f9cc1083c663a08917c5a78d78cdc8b5039d5bb6d2da3c8645c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DanStough/epok/releases/download/v0.1.2/epok_Linux_x86_64.tar.gz"
      sha256 "348a2cac2e4873e76f99746b09eeb229d925f321373041f11bc8d3f9d6637e94"
    end
    on_arm do
      url "https://github.com/DanStough/epok/releases/download/v0.1.2/epok_Linux_arm64.tar.gz"
      sha256 "12b4cf9b7b6a0d433f930f9c33781200de798e733d9e2eb72ef500ff36a84f97"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/epok"]
    end
  end

  # No zap stanza required
end
