# This file was generated by GoReleaser. DO NOT EDIT.
cask "epok" do
  desc "A CLI for working with Unix Timestamps & Timezones"
  homepage "https://github.com/DanStough/epok"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "epok"
  manpage "manpages/epok.1.gz"
  bash_completion "completions/epok.bash"
  zsh_completion "completions/epok.zsh"
  fish_completion "completions/epok.fish"

  on_macos do
    on_intel do
      url "https://github.com/DanStough/epok/releases/download/v0.1.1/epok_Darwin_x86_64.tar.gz"
      sha256 "b5e3d68f100c68f6aa2f9fdc2f64a4fc607a448fa72ac87a9670a8fe37c941ec"
    end
    on_arm do
      url "https://github.com/DanStough/epok/releases/download/v0.1.1/epok_Darwin_arm64.tar.gz"
      sha256 "98a218ac64a1ee13ab891c851fb0793fd4d8d034a030d057ae34e785ac38f561"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DanStough/epok/releases/download/v0.1.1/epok_Linux_x86_64.tar.gz"
      sha256 "0e97450e17f74eea75efedab0e6e8aaa62adaf2d9b4ebb89829df3d334a223a7"
    end
    on_arm do
      url "https://github.com/DanStough/epok/releases/download/v0.1.1/epok_Linux_arm64.tar.gz"
      sha256 "aaa37ea55f990c970081396f709e4bef98c1cc346f72061ae4955f286840ea55"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/epok"]
    end
  end

  # No zap stanza required
end
