# This file was generated by GoReleaser. DO NOT EDIT.
cask "epok" do
  desc "A CLI for working with Unix Timestamps & Timezones"
  homepage "https://github.com/DanStough/epok"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "epok"
  manpage "manpages/epok.1.gz"
  bash_completion "completions/epok.bash"
  zsh_completion "completions/epok.zsh"
  fish_completion "completions/epok.fish"

  on_macos do
    on_intel do
      url "https://github.com/DanStough/epok/releases/download/v0.2.0/epok_Darwin_x86_64.tar.gz"
      sha256 "9dcbda3b698cc41510c1d582ff6fc00e68a2f6c5b8442b9f4a5a4e1ae68f9cc4"
    end
    on_arm do
      url "https://github.com/DanStough/epok/releases/download/v0.2.0/epok_Darwin_arm64.tar.gz"
      sha256 "93bf41f51e2ecbcb6d31371b3f0153f86cbdfab81effc0f4f923a9408c3f135a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DanStough/epok/releases/download/v0.2.0/epok_Linux_x86_64.tar.gz"
      sha256 "cad9166037734e0e9296e333fa7d8c59b848e8711c02cc2b16cedb285327e950"
    end
    on_arm do
      url "https://github.com/DanStough/epok/releases/download/v0.2.0/epok_Linux_arm64.tar.gz"
      sha256 "22d21ea734dc1fa57ba269e850d5eab607077be6c499765b037e2f210e999f40"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/epok"]
    end
  end

  # No zap stanza required
end
